import hashlib
import json
import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from tools.validate_assets import validate


class ValidateAssetsTests(unittest.TestCase):
    def write_manifest(self, root: Path, assets: list[dict[str, object]]) -> None:
        manifest_path = root / "assets" / "manifest.json"
        manifest_path.parent.mkdir(parents=True, exist_ok=True)
        manifest_path.write_text(
            json.dumps(
                {"schema_version": 1, "asset_root": "assets/files", "assets": assets},
                indent=2,
            )
            + "\n",
            encoding="utf-8",
        )

    def add_asset(self, root: Path, name: str, content: bytes) -> dict[str, object]:
        path = root / "assets" / "files" / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)
        return {
            "path": path.relative_to(root).as_posix(),
            "sha256": hashlib.sha256(content).hexdigest(),
            "bytes": len(content),
            "media_type": "image/png",
            "source": "test fixture",
            "license": "internal-original",
            "provenance": "generated by the unit test",
        }

    def test_empty_manifest_is_a_valid_initial_state(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            self.write_manifest(root, [])
            self.assertEqual(validate(root), [])

    def test_valid_manifest_and_file_pass(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            entry = self.add_asset(root, "sample.png", b"not-a-real-png-fixture")
            self.write_manifest(root, [entry])
            self.assertEqual(validate(root), [])

    def test_missing_manifest_entry_and_wrong_hash_are_reported(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            entry = self.add_asset(root, "sample.png", b"fixture")
            entry["sha256"] = "0" * 64
            self.write_manifest(root, [entry])
            (root / "assets" / "files" / "unlisted.jpg").write_bytes(b"extra")

            errors = validate(root)

            self.assertTrue(any("sha256 does not match" in error for error in errors))
            self.assertTrue(any("not listed in manifest" in error for error in errors))

    def test_unsupported_file_and_secret_pattern_are_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            entry = self.add_asset(root, "secret.png", b"ghp_abcdefghijklmnopqrstuvwxyz123456")
            self.write_manifest(root, [entry])
            (root / "assets" / "files" / "payload.zip").write_bytes(b"archive")

            errors = validate(root)

            self.assertTrue(any("secret" in error for error in errors))
            self.assertTrue(any("unsupported or forbidden" in error for error in errors))


if __name__ == "__main__":
    unittest.main()
